default:
  name: argo-wf
  namespace: argo-workflows

rbac:
  - name: cluster-admins
    clusterWide: true
    group: cluster-admins
    precedence: 100
    clusterRole: admin 

argo-workflows:
  workflow:
    serviceAccount:
      create: true
      name: "argo-workflows"
    rbac:
      create: true
  singleNamespace: false
  controller:
    workflowNamespaces:
      - argo-wf-demo
      - argo-workflows

    replicas: 2 
    pdb:
      enabled: true
      minAvailable: 1
    serviceMonitor:
      enabled: true
    metricsConfig:
      enabled: true
    telemetryConfig:
      enabled: true  
    workflowDefaults:
      spec:
        serviceAccountName: argo-workflows

  server:
    autoscaling:
      enabled: true
      minReplicas: 2 # should be strictly greater than PDB minAvailable
    pdb:
      enabled: true
      minAvailable: 1

    authModes:
      - sso
      - client

    sso:
      enabled: false
  
