dex:
  replicaCount: 1

  commonLabels: 
    app.kubernetes.io/part-of: argo-workflows

  image:
    repository: ghcr.io/dexidp/dex
    pullPolicy: IfNotPresent

  https:
    enabled: false

  grpc:
    enabled: true

  configSecret:
    create: true
    name: "dex-server-secret"

  config: {}

  serviceAccount:
    create: false
    name: dex-server

  rbac:
    create: true
    createClusterScoped: true

  podSecurityContext: 
    # capabilities:
    #     drop:
    #       - ALL
    runAsNonRoot: true
    # allowPrivilegeEscalation: false

  securityContext: 
    seccompProfile:
      type: RuntimeDefault

  resources: 
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 256Mi

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
