---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.ocp_namespace.name }}
  annotations:
    openshift.io/description: {{ .Values.ocp_namespace.description }}
    {{- with .Values.ocp_namespace.annotations -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- with  .Values.ocp_namespace.labels -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
