{{- if .Values.enabled }}
{{- range $operator := .Values.operators }}
{{- if .operatorGroup }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  targetNamespaces: 
    {{ tpl .targetNamespaces $ }}
{{- end }}
{{- end }}
{{- end }}