{{- if .Values.enabled }}
{{- if .Values.operator }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.operator.namespace }}
spec:
  channel: {{  .Values.operator.channel | default  .Values.default.channel }}
  installPlanApproval: {{ .Values.operator.installPlanApproval | default .Values.default.installPlanApproval }}
  name: {{ .Values.operator.name }}
  source: {{ .Values.operator.source | default  .Values.default.source }}
  sourceNamespace: {{ .Values.operator.sourceNamespace | default .Values.default.sourceNamespace }}
  {{- if .Values.operator.version }}
  startingCSV: {{ .Values.operator.version }}
  {{- end }}
{{- end }}
{{- end }}

