kind: ServiceAccount
apiVersion: v1
metadata:
  name: dex-server
  namespace: argo-workflows
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.dex: >-
      https://dex-server-argo-workflows.apps.ocp4.whatever.out-of-my-head.de/api/dex/callback
secrets:
  - name: dex-sa-token
