{{- range $rbac := $.Values.rbac }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $rbac.name }}-sa
  namespace: {{ $.Values.default.namespace }}
  annotations:
    workflows.argoproj.io/rbac-rule: "'{{ $rbac.group }}' in groups"
    workflows.argoproj.io/rbac-rule-precedence: {{ $rbac.precedence | quote }}
automountServiceAccountToken: true
secrets:
  - name: {{ $rbac.name }}-sa-token
{{- end }}