{{- if .Values.secret.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
spec:
  data:
    - remoteRef:
        conversionStrategy: {{ .Values.secret.conversionStrategy | default "default" }}
        key: {{ .Values.secret.name }}
        property: {{ .Values.secret.property }}
      secretKey: {{ .Values.secret.secretKey }}
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secret.secretStore }}
  target:
    creationPolicy: Owner
    name: {{ .Values.secret.name }}
{{- end }}
