---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appName }}
spec:
  to:
    kind: Service
    name: {{ .Values.appName }}-svc
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
